name: Main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and collect coverage
        run: |
            ./gradlew build
            ./gradlew test

      - uses: qltyai/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          file: build/reports/jacoco/test/jacocoTestReport.xml
          add-prefix: src/main/kotlin
