name: Main
on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and collect coverage
        run: |
            ./gradlew build
            ./gradlew test

      - name: Debug qlty-coverage
        run: |
            echo $GITHUB_SHA
            curl --fail --location https://qlty-releases.s3.amazonaws.com/qlty-coverage/latest/qlty-coverage-x86_64-unknown-linux-gnu.tar.xz > qlty-coverage
            chmod +x qlty-coverage
            QLTY_COVERAGE_TOKEN=ec1eb8f8-bb9a-4364-8c43-d30ee030f467 QLTY_PROJECT_ID=ec1eb8f8-bb9a-4364-8c43-d30ee030f467 ./qlty-coverage --verbose --upload build/reports/jacoco/test/jacocoTestReport.xml

      - uses: qltyai/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          file: build/reports/jacoco/test/jacocoTestReport.xml
